/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnimalsIndexRouteImport } from './routes/animals.index'
import { Route as AnimalsDogsIndexRouteImport } from './routes/animals.dogs.index'
import { Route as AnimalsDogsCockerRouteImport } from './routes/animals.dogs.cocker'

const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsDogsIndexRoute = AnimalsDogsIndexRouteImport.update({
  id: '/animals/dogs/',
  path: '/animals/dogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsDogsCockerRoute = AnimalsDogsCockerRouteImport.update({
  id: '/animals/dogs/cocker',
  path: '/animals/dogs/cocker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/animals': typeof AnimalsIndexRoute
  '/animals/dogs/cocker': typeof AnimalsDogsCockerRoute
  '/animals/dogs': typeof AnimalsDogsIndexRoute
}
export interface FileRoutesByTo {
  '/animals': typeof AnimalsIndexRoute
  '/animals/dogs/cocker': typeof AnimalsDogsCockerRoute
  '/animals/dogs': typeof AnimalsDogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/animals/': typeof AnimalsIndexRoute
  '/animals/dogs/cocker': typeof AnimalsDogsCockerRoute
  '/animals/dogs/': typeof AnimalsDogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/animals' | '/animals/dogs/cocker' | '/animals/dogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/animals' | '/animals/dogs/cocker' | '/animals/dogs'
  id: '__root__' | '/animals/' | '/animals/dogs/cocker' | '/animals/dogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnimalsIndexRoute: typeof AnimalsIndexRoute
  AnimalsDogsCockerRoute: typeof AnimalsDogsCockerRoute
  AnimalsDogsIndexRoute: typeof AnimalsDogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/dogs/': {
      id: '/animals/dogs/'
      path: '/animals/dogs'
      fullPath: '/animals/dogs'
      preLoaderRoute: typeof AnimalsDogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/dogs/cocker': {
      id: '/animals/dogs/cocker'
      path: '/animals/dogs/cocker'
      fullPath: '/animals/dogs/cocker'
      preLoaderRoute: typeof AnimalsDogsCockerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AnimalsIndexRoute: AnimalsIndexRoute,
  AnimalsDogsCockerRoute: AnimalsDogsCockerRoute,
  AnimalsDogsIndexRoute: AnimalsDogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
